# Site settings
title: Undoing in Git
email: jacqnelson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This awesome blog is for teaching you all the awesome things about undoing in git. Isn't that awesome!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: spaceotterin
github_username:  spaceotterinspace

# Build settings
markdown: kramdown
